sampler:
  _target_: lightning_module.resshift_with_checkpoint
  autoencoder:
    _target_: ldm.models.autoencoder.VQModelTorch
    # ckpt_path: weights/autoencoder_vq_f4.pth
    # use_fp16: True
    # params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      padding_mode: zeros

  model:
    _target_: models.unet.UNetModelSwin
    #ckpt_path: /mnt/lustre/zsyue/projects/ResShift/SR/models/swin_v2/Esr256_ImageNet_rescale/S5_K2.0_P0.3/ema_ckpts/ema_model_300000.pth
    # ckpt_path: ~
    # params:
    image_size: 64
    in_channels: 3
    model_channels: 160
    # out_channels: ${autoencoder.params.embed_dim}
    out_channels: 3
    attention_resolutions: [64,32,16,8]
    dropout: 0
    channel_mult: [1, 2, 2, 4]
    num_res_blocks: [2, 2, 2, 2]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 32
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 192
    window_size: 8
    mlp_ratio: 4
    cond_lq: True
    lq_size: 64

  model_ckpt: weights/resshift_realsrx4_s4_v3.pth
  autoencoder_ckpt: weights/autoencoder_vq_f4.pth

  base_diffusion:
    _target_: models.script_util.create_gaussian_diffusion
    # params:
    sf: 4
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 4
    min_noise_level: 0.2
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True