uq_method:
  _target_: lightning_module.resshift_with_checkpoint
  autoencoder: null

  model:
    _target_: models.unet.UNetModelSwin
    image_size: 32 # LQ size
    in_channels: 1
    # model_channels: 160
    model_channels: 32
    out_channels: 1
    # attention_resolutions: [64,32,16,8]
    attention_resolutions: [16,8, 8, 4]
    dropout: 0
    channel_mult: [1, 2, 2, 4]
    # channel_mult: [1, 2]
    num_res_blocks: [2, 2, 2, 2]
    conv_resample: True
    dims: 2 # convolution dimensions? 
    use_fp16: False
    num_head_channels: 8
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 192
    window_size: 8
    mlp_ratio: 4
    cond_lq: True
    lq_size: 32 # LQ size

  base_diffusion:
    _target_: models.script_util.create_gaussian_diffusion
    sf: 8
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 4
    min_noise_level: 0.2
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: False


experiment:
  experiment_name: "resshift"
  exp_dir: "experiments"
wandb:
  project: resshift
  entity: uq-regression
  mode: online

trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  strategy: ddp
  devices: [1, 7]
  min_epochs: 80
  max_epochs: 100
  log_every_n_steps: 20
  enable_progress_bar: True